# Generated by Django 3.0.8 on 2020-07-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pariwisataapi', '0005_pariwisata_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pariwisata',
            name='images',
            field=models.TextField(default=''),
        ),
    ]
